# Generated by Django 5.2.5 on 2025-08-26 16:01

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('main', '0004_alter_product_main_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', on_delete=django.db.models.deletion.CASCADE, to='main.productsize'),
        ),
    ]
